### ISSUE TITLE
เจอบัค

### ISSUE THREAD

**Issue by ChawinKatpark** [ChawinKatpark/ScratchProject18#16]
ตอนนี้พบปัญหาบัค **ปุ่มกดไม่ติด** (ความจริงไม่ใช่บัคหรอกคนเล่นหัวร้อนมากกว่า (ตัวละครจะกระโดดต่อเมื่อกด spacebar หลังจากลงมาถึงพื้นแล้วแต่บางครั้งคนเล่นกดspacebarก่อนจะถึงพื้นทำให้โดดไม่ติด))

**Comment by Yay50210** [comment]
สิ่งที่เกิดขึ้นยังไม่เรียกว่าบัคเกมแต่เป็นเพียง เพราะว่าหากตัวละครเรายังไม่ถึงพื้น จะยังไม่สามารถกระโดดได้ ต้องรอตัวละครถึงพื้นก่อน

**Comment by ChawinKatpark** [comment]
ตอนนี้แก้ปัญหาเรียบร้อยแล้ว
